export const colorMap = {
'poison': '#CFB7ED',
'electric': '#E2E2A0',
'fighting': '#FCC1B0',
'flying':'#B2D2E8',
'normal': '#DDCBD0',
'ground': '#F4D1A6',
'ghost': '#D7C2D7',
'steel': '#C2D4CE',
'fire': '#EDC2C4',
'rock': '#C5AEA8',
'bug': '#C1E0C8',
'water': '#CBD5ED',
'grass': '#C0D4C8',
'psychic': '#DDC0CF',
'ice': '#C7D7DF',
'dark': '#C6C5E3',
'fairy': '#E4C0CF',
'unknown': '#C0DFDD',
'shadow': '#CACACA'
}